### PR TITLE
Replace 'event.srcElement' with 'this' when no event object is passed to event handler

### PR DESCRIPTION
**Pull request by AntonKhorev**
The main concern of this fix is `gasket5` example used in [Coursera MOOC](https://class.coursera.org/webgl-001).

Slider controls in `gasket5` don't work on Firefox because there's no `srcElement` attribute in [`Event` interface](http://www.w3.org/TR/DOM-Level-2-Events/events.html#Events-interface). Also there's no standard global `event` object. It is present in some browsers for compatibility with older versions of Internet Explorer, which you don't need because those versions don't support `canvas` and `webgl`.

The easiest fix is to use `this` instead of `event.srcElement`.

### CODE REVIEW

**Comment by esangel** [comment]
Interesting. I had recently replaced the use of srcElement by event.target.value but apparently this does not work in Firefox.

---

Ed Angel

Founding Director, Art, Research, Technology and Science Laboratory (ARTS Lab)
Professor Emeritus of Computer Science, University of New Mexico

1017 Sierra Pinon
Santa Fe, NM 87501
505-984-0136 (home)         angel@cs.unm.edu mailto:angel@cs.unm.edu
505-453-4944 (cell)                 http://www.cs.unm.edu/~angel http://www.cs.unm.edu/~angel

**Comment by AntonKhorev** [comment]
`event.target` is another option. It works in Firefox.

`srcElement` is still present in some files like `Chap5/ortho2.js`. This pull request replaces it and removes repeated `id="slide"` in `Chap9/figure.html` and `Chap9/robotArm.html`.

**Comment by esangel** [comment]
Thanks for your offer. I’ll have them all updated by tomorrow morning. Since I have a couple of places to update, I’ll update them myself.

I had replaced srcElement  target on one of my sites but had neglected to do it the other.

---

Ed Angel

Founding Director, Art, Research, Technology and Science Laboratory (ARTS Lab)
Professor Emeritus of Computer Science, University of New Mexico

1017 Sierra Pinon
Santa Fe, NM 87501
505-984-0136 (home)         angel@cs.unm.edu mailto:angel@cs.unm.edu
505-453-4944 (cell)                 http://www.cs.unm.edu/~angel http://www.cs.unm.edu/~angel

**Comment by AntonKhorev** [comment]
What's left here is repeated `input id="slide"` (ids have to be unique), but it doesn't cause any problems.

**Comment by AntonKhorev** [comment]
Coursera's [gasket5.js](http://www.cs.unm.edu/~angel/COURSERA/CODE/EXAMPLES/gasket5.js) is different and still relies on the global event object which is undefined in Firefox.

This line:

```
document.getElementById("slider").onchange = function(target) {
```

should be replaced with

```
document.getElementById("slider").onchange = function(event) {
```

**Comment by esangel** [comment]
Fixed. Thanks.

---

Ed Angel

Founding Director, Art, Research, Technology and Science Laboratory (ARTS Lab)
Professor Emeritus of Computer Science, University of New Mexico

1017 Sierra Pinon
Santa Fe, NM 87501
505-984-0136 (home)         angel@cs.unm.edu mailto:angel@cs.unm.edu
505-453-4944 (cell)                 http://www.cs.unm.edu/~angel http://www.cs.unm.edu/~angel

**Comment by esangel** [comment]
I’m not sure I understand this one. Where are the repeated id’s?

---

Ed Angel

Founding Director, Art, Research, Technology and Science Laboratory (ARTS Lab)
Professor Emeritus of Computer Science, University of New Mexico

1017 Sierra Pinon
Santa Fe, NM 87501
505-984-0136 (home)         angel@cs.unm.edu mailto:angel@cs.unm.edu
505-453-4944 (cell)                 http://www.cs.unm.edu/~angel http://www.cs.unm.edu/~angel

**Comment by AntonKhorev** [comment]
Repeated ids are in `Chap9/figure.html` and `Chap9/robotArm.html` . Different slider inputs have the same `id="slide"`.

``` html
<div id="slider0">
torso angle -180 <input id="slide" type="range"
 min="-180" max="180" step="10" value="0"
  />
 180
</div><br/>
<div id="slider10">
head2 angle -180 <input id="slide" type="range"
 min="-180" max="180" step="10" value="0"
  />
 180
</div><br/>

<div id="slider1">
head1 angle -180 <input id="slide" type="range"
 min="-180" max="180" step="10" value="0"
  />
 180
</div><br/>
```

**Comment by esangel** [comment]
I see what happened. Will fix. Thanks again.

---

Ed Angel

Founding Director, Art, Research, Technology and Science Laboratory (ARTS Lab)
Professor Emeritus of Computer Science, University of New Mexico

1017 Sierra Pinon
Santa Fe, NM 87501
505-984-0136 (home)         angel@cs.unm.edu mailto:angel@cs.unm.edu
505-453-4944 (cell)                 http://www.cs.unm.edu/~angel http://www.cs.unm.edu/~angel

**Pull request closed without merging**
